### PR TITLE
set up docker test fandango

### PR DESCRIPTION
**Pull request by xuanlv0703**
i had try set up fandango. but now get problem with setting up database. Hope you can help it.
Thanks.

### CODE REVIEW

**Comment by modius** [comment]
Remove .vagrant folder. This should be in .gitignore

**Comment by modius** [comment]
Add this.bUseENV=true to project-fandango farcryConstructor.cfm to allow configuration with environment variables. See project-Chelsea for an example.

**Comment by modius** [comment]
Change vagrant references from Chelsea to fandango. Rename Chelsea.sql to fandango.sql; open file and update database create statement.

Change environment variables for data source in vagrant file to reflect fandango database and data source name.

**Comment by xuanlv0703** [comment]
i had did as you said. now where can i access to database on my local. Could you look it and give me advise

**Comment by xuanlv0703** [comment]
and Have problem with pust www/farcryconstructor.cfm to server. don't have permision

**Comment by modius** [comment]
Have updated `project-fandango`, hopefully that's all you need:
https://github.com/farcrycore/project-fandango/commit/5d73875257a252c95bd2b86caf7cc8e0d1d7ab9c

The mySQL container will run the installation sql (fandango.sql) when its first created.  To force workbench to recreate the container:
```
vagrant destroy mysql
vagrant up mysql
```
You can check the `stdout` log for the container with:
```
vagrant docker-logs mysql
```

**Comment by modius** [comment]
To access the mysql database with a mysql client (eg. mysql workbench) you will need to temporarily publish a port on the container.  Add the following just below the `docker.expose`:
```
docker.ports = %w(3306:3306)
docker.expose = %w(3306)
```

This will allow you to connect to mysql at `workbench.dev:3306`.  Don't commit the ports entry.

**Comment by modius** [comment]
You still need to remove the contents of `.vagrant` from the pull request.  Its now in the `.gitignore` file but the contents are still in the commit. 

Not sure how you would back those out of the PR without closing it and trying a new PR.

**Pull request closed without merging**
